int          AddFontResourceA(LPCSTR);
int          AddFontResourceW(LPCWSTR);
HENHMETAFILE CopyEnhMetaFileA(HENHMETAFILE,LPCSTR);
HENHMETAFILE CopyEnhMetaFileW(HENHMETAFILE,LPCWSTR);
HMETAFILE    CopyMetaFileA(HMETAFILE,LPCSTR);
HMETAFILE    CopyMetaFileW(HMETAFILE,LPCWSTR);
HBITMAP      CreateBitmapIndirect( BITMAP_P);
HBRUSH       CreateBrushIndirect( LOGBRUSH_P);
HCOLORSPACE  CreateColorSpaceA(LPLOGCOLORSPACEA);
HCOLORSPACE  CreateColorSpaceW(LPLOGCOLORSPACEW);
HDC          CreateDCA(LPCSTR,LPCSTR,LPCSTR, DEVMODEA_P);
HDC          CreateDCW(LPCWSTR,LPCWSTR,LPCWSTR, DEVMODEW_P);
HRGN         CreateEllipticRgnIndirect(LPCRECT);
HDC          CreateEnhMetaFileA(HDC,LPCSTR,LPCRECT,LPCSTR);
HDC          CreateEnhMetaFileW(HDC,LPCWSTR,LPCRECT,LPCWSTR);
HFONT        CreateFontIndirectA( LOGFONTA_P);
HFONT        CreateFontIndirectW( LOGFONTW_P);
HDC          CreateICA(LPCSTR,LPCSTR,LPCSTR, DEVMODEA_P);
HDC          CreateICW(LPCWSTR,LPCWSTR,LPCWSTR, DEVMODEW_P);
HICON        CreateIconFromResource(PBYTE,DWORD,BOOL,DWORD);
HICON        CreateIconIndirect(PICONINFO);
HDC          CreateMetaFileA(LPCSTR);
HDC          CreateMetaFileW(LPCWSTR);
HPALETTE     CreatePalette( LOGPALETTE_P);
HPEN         CreatePenIndirect( LOGPEN_P);
HRGN         CreateRectRgnIndirect(LPCRECT);
BOOL         FillRect(HDC,LPCRECT,HBRUSH);
HCURSOR      LoadCursorA(HINSTANCE,LPCSTR);
HCURSOR      LoadCursorW(HINSTANCE,LPCWSTR);
BOOL         PlayEnhMetaFile(HDC,HENHMETAFILE,LPCRECT);
BOOL         RectInRegion(HRGN,LPCRECT);
BOOL         RectVisible(HDC,LPCRECT);
ATOM         RegisterClassA(WNDCLASSA_P);
ATOM         RegisterClassW(WNDCLASSW_P);
BOOL         RemoveFontResourceA(LPCSTR);
BOOL         RemoveFontResourceW(LPCWSTR);
HDC          ResetDCA(HDC, DEVMODEA_P);
HDC          ResetDCW(HDC, DEVMODEW_P);
HPALETTE     SelectPalette(HDC,HPALETTE,BOOL);
BOOL         SetColorAdjustment(HDC, COLORADJUSTMENT_P);
BOOL         SetDeviceGammaRamp(HDC,PVOID);
BOOL         SetICMProfileA(HDC,LPSTR);
BOOL         SetICMProfileW(HDC,LPWSTR);
COLORREF     SetPixel(HDC,int,int,COLORREF);
BOOL         SetPixelV(HDC,int,int,COLORREF);
COLORREF     SetTextColor(HDC,COLORREF);
BOOL         SetWorldTransform(HDC, XFORM_P);
BOOL         DestroyCursor(HCURSOR);
HCURSOR      SetCursor(HCURSOR);
HCURSOR      GetCursor(void);
BOOL         GetCursorPos(LPPOINT);
BOOL         SetCursorPos(int,int);
BOOL         GetCursorInfo(PCURSORINFO);
/*COLORREF     GetDCPenColor(HDC);*/
COLORREF     SetDCPenColor(HDC,COLORREF);
/*COLORREF     GetDCBrushColor(HDC);*/
COLORREF     SetDCBrushColor(HDC,COLORREF);
HDC          GetWindowDC(HWND);
HDC          GetDCEx(HWND,HRGN,DWORD);
