# This file was used to recover from a problem with the funcs-rest.h file
grep -ih ANGLEARC *.h
grep -ih ARC *.h
grep -ih ARCTO *.h
grep -ih BITBLT *.h
grep -ih CHORD *.h
grep -ih CREATEDIBITMAP *.h
grep -ih CREATEFONTA *.h
grep -ih CREATEFONTW *.h
grep -ih CREATEROUNDRECTRGN *.h
grep -ih CREATEWINDOWEXA *.h
grep -ih CREATEWINDOWEXW *.h
grep -ih EXTESCAPE *.h
grep -ih EXTTEXTOUTA *.h
grep -ih EXTTEXTOUTW *.h
grep -ih GETCHARACTERPLACEMENTA *.h
grep -ih GETCHARACTERPLACEMENTW *.h
grep -ih GETDIBITS *.h
grep -ih GETGLYPHOUTLINEA *.h
grep -ih GETGLYPHOUTLINEW *.h
grep -ih GETTEXTEXTENTEXPOINTA *.h
grep -ih GETTEXTEXTENTEXPOINTW *.h
grep -ih MASKBLT *.h
grep -ih PATBLT *.h
grep -ih PIE *.h
grep -ih PLGBLT *.h
grep -ih ROUNDRECT *.h
grep -ih SCALEVIEWPORTEXTEX *.h
grep -ih SCALEWINDOWEXTEX *.h
grep -ih SETDIBITS *.h
grep -ih SETDIBITSTODEVICE *.h
grep -ih STRETCHBLT *.h
grep -ih STRETCHDIBITS *.h
grep -ih TABBEDTEXTOUTA *.h
grep -ih TABBEDTEXTOUTW *.h

