int          AddFontResourceA(LPCSTR);
int          AddFontResourceW(LPCWSTR);
BOOL         AnimatePalette(HPALETTE,UINT,UINT, PALETTEENTRY_P);
int          ChoosePixelFormat(HDC,  PIXELFORMATDESCRIPTOR_P);
HBITMAP      CreateBitmap(int,int,UINT,UINT,PCVOID);
HBRUSH       CreateDIBPatternBrushPt(PCVOID,UINT);
HRGN         CreatePolyPolygonRgn( POINT_P, INT_P,int,int);
HRGN         CreatePolygonRgn( POINT_P,int,int);
BOOL         CreateScalableFontResourceA(DWORD,LPCSTR,LPCSTR,LPCSTR);
BOOL         CreateScalableFontResourceW(DWORD,LPCWSTR,LPCWSTR,LPCWSTR);
BOOL         DPtoLP(HDC,LPPOINT,int);
int          DescribePixelFormat(HDC,int,UINT,LPPIXELFORMATDESCRIPTOR);
int          DrawEscape(HDC,int,int,LPCSTR);
HPEN         ExtCreatePen(DWORD,DWORD, LOGBRUSH_P,DWORD, DWORD_P);
HRGN         ExtCreateRegion( XFORM_P,DWORD, RGNDATA_P);
BOOL         FixBrushOrgEx(HDC,int,int,LPPOINT);
BOOL         GdiComment(HDC,UINT, BYTE_P);
BOOL         GdiFlush(void);
DWORD        GdiGetBatchLimit(void);
BOOL         LPtoDP(HDC,LPPOINT,int);
BOOL         ModifyWorldTransform(HDC, XFORM_P,DWORD);
BOOL         MoveToEx(HDC,int,int,LPPOINT);
BOOL         OffsetViewportOrgEx(HDC,int,int,LPPOINT);
BOOL         OffsetWindowOrgEx(HDC,int,int,LPPOINT);
BOOL         PlayEnhMetaFileRecord(HDC,LPHANDLETABLE, ENHMETARECORD_P,UINT);
BOOL         PlayMetaFileRecord(HDC,LPHANDLETABLE,LPMETARECORD,UINT);
BOOL         PolyBezier(HDC, POINT_P,DWORD);
BOOL         PolyBezierTo(HDC, POINT_P,DWORD);
BOOL         PolyDraw(HDC, POINT_P, BYTE_P,int);
BOOL         PolyPolygon(HDC, POINT_P, INT_P,int);
BOOL         PolyPolyline(HDC, POINT_P, DWORD_P,DWORD);
BOOL         PolyTextOutA(HDC, POLYTEXTA_P,int);
BOOL         PolyTextOutW(HDC, POLYTEXTW_P,int);
BOOL         Polygon(HDC, POINT_P,int);
BOOL         Polyline(HDC, POINT_P,int);
BOOL         PolylineTo(HDC, POINT_P,DWORD);
LONG         SetBitmapBits(HBITMAP,DWORD,PCVOID);
BOOL         SetBitmapDimensionEx(HBITMAP,int,int,LPSIZE);
UINT         SetBoundsRect(HDC,LPCRECT,UINT);
BOOL         SetBrushOrgEx(HDC,int,int,LPPOINT);
UINT         SetDIBColorTable(HDC,UINT,UINT, RGBQUAD_P);
HENHMETAFILE SetEnhMetaFileBits(UINT, BYTE_P);
HMETAFILE    SetMetaFileBitsEx(UINT, BYTE_P);
UINT         SetPaletteEntries(HPALETTE,UINT,UINT, PALETTEENTRY_P);
BOOL         SetPixelFormat(HDC,int,PIXELFORMATDESCRIPTOR_P);
BOOL         SetViewportExtEx(HDC,int,int,LPSIZE);
BOOL         SetViewportOrgEx(HDC,int,int,LPPOINT);
HENHMETAFILE SetWinMetaFileBits(UINT, BYTE_P,HDC, METAFILEPICT_P);
BOOL         SetWindowExtEx(HDC,int,int,LPSIZE);
BOOL         SetWindowOrgEx(HDC,int,int,LPPOINT);
int          StartDocA(HDC, DOCINFOA_P);
int          StartDocW(HDC, DOCINFOW_P);
BOOL         TextOutA(HDC,int,int,LPCSTR,int);
BOOL         TextOutW(HDC,int,int,LPCWSTR,int);
BOOL         UpdateICMRegKeyA(DWORD,DWORD,LPSTR,UINT);
BOOL         UpdateICMRegKeyW(DWORD,DWORD,LPWSTR,UINT);
